import type { Product, Category, QuickCategory, Banner } from "../types";

export const mockBanners: Banner[] = [
  {
    id: 1,
    imageUrl: "https://picsum.photos/seed/kitchen88/750/400",
    title: "今天就开始升级\n您的厨房",
    badge: "季节限定",
    buttonText: "去购物",
  },
  {
    id: 2,
    imageUrl: "https://picsum.photos/seed/fresh77/750/400",
    title: "新鲜直达\n品质生活",
    badge: "限时特惠",
    buttonText: "立即抢购",
  },
  {
    id: 3,
    imageUrl: "https://picsum.photos/seed/member66/750/400",
    title: "尊享会员\n专属优惠",
    badge: "会员专享",
    buttonText: "了解详情",
  },
];

export const mockQuickCategories: QuickCategory[] = [
  { id: 1, name: "扫码购", icon: "scan-outline", color: "#434751" },
  { id: 2, name: "线上购物", icon: "bag-handle-outline", color: "#434751" },
  { id: 3, name: "续费", icon: "card-outline", color: "#434751" },
  { id: 4, name: "会员权益", icon: "diamond-outline", color: "#434751" },
  { id: 5, name: "会员日", icon: "calendar-outline", color: "#434751" },
];

export interface FlashSaleProduct {
  id: number;
  name: string;
  imageUrl: string;
  originalPrice: string;
  salePrice: string;
  discount: string;
}

export const mockFlashSaleProducts: FlashSaleProduct[] = [
  {
    id: 1,
    name: "山姆会员商店 奢华智能手表 Series X",
    imageUrl: "https://picsum.photos/seed/watch11/300/300",
    originalPrice: "199.00",
    salePrice: "119.40",
    discount: "-40%",
  },
  {
    id: 2,
    name: "精选比利时松露巧克力礼盒",
    imageUrl: "https://picsum.photos/seed/choco22/300/300",
    originalPrice: "32.00",
    salePrice: "24.00",
    discount: "-25%",
  },
  {
    id: 3,
    name: "高端降噪无线耳机 旗舰版",
    imageUrl: "https://picsum.photos/seed/headphone33/300/300",
    originalPrice: "249.00",
    salePrice: "211.65",
    discount: "-15%",
  },
  {
    id: 4,
    name: "进口有机混合坚果礼盒",
    imageUrl: "https://picsum.photos/seed/nuts44/300/300",
    originalPrice: "88.00",
    salePrice: "59.90",
    discount: "-32%",
  },
];

export const mockCategories: Category[] = [
  {
    id: 1,
    name: "生鲜美食",
    iconName: "restaurant-outline",
    description: "产地直采，新鲜到家。",
    parentId: null,
    children: [
      { id: 11, name: "新鲜蔬果", iconName: "leaf-outline", parentId: 1, imageUrl: "https://picsum.photos/seed/vegs/300/300", productCount: 56, description: "有机与时令精选" },
      { id: 12, name: "肉类海鲜", iconName: "fish-outline", parentId: 1, imageUrl: "https://picsum.photos/seed/meat/300/300", productCount: 42 },
      { id: 13, name: "乳品烘焙", iconName: "cafe-outline", parentId: 1, imageUrl: "https://picsum.photos/seed/dairy/300/300", productCount: 28 },
      { id: 14, name: "手工面包", iconName: "bread-slice-outline", parentId: 1 },
      { id: 15, name: "蛋糕甜点", iconName: "ice-cream-outline", parentId: 1 },
    ],
  },
  {
    id: 2,
    name: "休闲零食",
    iconName: "fast-food-outline",
    description: "精选各地美味零食。",
    parentId: null,
    children: [
      { id: 21, name: "坚果炒货", iconName: "nutrition-outline", parentId: 2, imageUrl: "https://picsum.photos/seed/nuts99/300/300", productCount: 38 },
      { id: 22, name: "饼干糕点", iconName: "pizza-outline", parentId: 2, imageUrl: "https://picsum.photos/seed/biscuit/300/300", productCount: 25 },
      { id: 23, name: "糖果巧克力", iconName: "heart-outline", parentId: 2, imageUrl: "https://picsum.photos/seed/candy/300/300", productCount: 31 },
      { id: 24, name: "膨化食品", iconName: "flame-outline", parentId: 2 },
    ],
  },
  {
    id: 3,
    name: "家居生活",
    iconName: "home-outline",
    description: "让生活更舒适便捷。",
    parentId: null,
    children: [
      { id: 31, name: "衣物清洁", iconName: "water-outline", parentId: 3, imageUrl: "https://picsum.photos/seed/clean/300/300", productCount: 20 },
      { id: 32, name: "纸品", iconName: "document-outline", parentId: 3, imageUrl: "https://picsum.photos/seed/paper/300/300", productCount: 15 },
      { id: 33, name: "收纳整理", iconName: "cube-outline", parentId: 3, imageUrl: "https://picsum.photos/seed/storage/300/300", productCount: 18 },
    ],
  },
  {
    id: 4,
    name: "个护美妆",
    iconName: "sparkles-outline",
    description: "呵护每一天。",
    parentId: null,
    children: [
      { id: 41, name: "洗发护发", iconName: "water-outline", parentId: 4, imageUrl: "https://picsum.photos/seed/shampoo/300/300", productCount: 22 },
      { id: 42, name: "口腔护理", iconName: "happy-outline", parentId: 4, imageUrl: "https://picsum.photos/seed/oral/300/300", productCount: 12 },
      { id: 43, name: "面部护肤", iconName: "flower-outline", parentId: 4, imageUrl: "https://picsum.photos/seed/skincare/300/300", productCount: 35 },
    ],
  },
  {
    id: 5,
    name: "数码家电",
    iconName: "laptop-outline",
    description: "科技改变生活。",
    parentId: null,
    children: [
      { id: 51, name: "手机数码", iconName: "phone-portrait-outline", parentId: 5, imageUrl: "https://picsum.photos/seed/phone/300/300", productCount: 45 },
      { id: 52, name: "电脑办公", iconName: "desktop-outline", parentId: 5, imageUrl: "https://picsum.photos/seed/laptop/300/300", productCount: 30 },
      { id: 53, name: "家用电器", iconName: "tv-outline", parentId: 5, imageUrl: "https://picsum.photos/seed/appliance/300/300", productCount: 28 },
    ],
  },
  {
    id: 6,
    name: "厨房用品",
    iconName: "cafe-outline",
    description: "美食从好工具开始。",
    parentId: null,
    children: [
      { id: 61, name: "锅具", iconName: "flame-outline", parentId: 6, imageUrl: "https://picsum.photos/seed/pots/300/300", productCount: 16 },
      { id: 62, name: "刀具", iconName: "cut-outline", parentId: 6, imageUrl: "https://picsum.photos/seed/knives/300/300", productCount: 10 },
      { id: 63, name: "餐具", iconName: "restaurant-outline", parentId: 6, imageUrl: "https://picsum.photos/seed/tableware/300/300", productCount: 14 },
    ],
  },
  {
    id: 7,
    name: "居家装饰",
    iconName: "color-palette-outline",
    description: "打造理想空间。",
    parentId: null,
    children: [
      { id: 71, name: "灯饰", iconName: "bulb-outline", parentId: 7, imageUrl: "https://picsum.photos/seed/lamp/300/300", productCount: 20 },
      { id: 72, name: "窗帘", iconName: "grid-outline", parentId: 7, imageUrl: "https://picsum.photos/seed/curtain/300/300", productCount: 12 },
      { id: 73, name: "装饰画", iconName: "image-outline", parentId: 7, imageUrl: "https://picsum.photos/seed/painting/300/300", productCount: 18 },
    ],
  },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "有机厨房必需品组合",
    description: "为您厨房精心挑选的高品质谷物、冷压油和手工香料组合。",
    price: "89.90",
    originalPrice: "129.00",
    profit_rate: "0.15",
    images: ["https://picsum.photos/seed/kitchen1/600/600"],
    sales: 3280,
    tags: ["member_exclusive"],
  },
  {
    id: 2,
    name: "65寸超高清OLED智能电视",
    description: "纯净黑色与鲜艳色彩的完美融合，为您带来电影般的视觉盛宴。库存有限。",
    price: "1249.00",
    originalPrice: "1599.00",
    profit_rate: "0.12",
    images: ["https://picsum.photos/seed/tv2/600/600"],
    sales: 1856,
    tags: ["new"],
  },
  {
    id: 3,
    name: "三只松鼠每日坚果混合装",
    description: "精选6种坚果搭配果干，每日一包，营养均衡，750g共30小袋。",
    price: "89.90",
    originalPrice: "129.00",
    profit_rate: "0.18",
    images: ["https://picsum.photos/seed/nuts3/600/600"],
    sales: 5620,
    tags: ["hot"],
  },
  {
    id: 4,
    name: "蒙牛特仑苏纯牛奶礼盒装",
    description: "优质牧场鲜奶，3.8g优质乳蛋白，醇香浓郁，250ml×12盒装。",
    price: "49.90",
    originalPrice: "65.00",
    profit_rate: "0.10",
    images: ["https://picsum.photos/seed/milk4/600/600"],
    sales: 8920,
  },
  {
    id: 5,
    name: "金龙鱼食用调和油",
    description: "非转基因原料，科学配比1:1:1，满足全家烹饪需求，5L家庭装。",
    price: "58.80",
    originalPrice: "72.00",
    profit_rate: "0.08",
    images: ["https://picsum.photos/seed/oil5/600/600"],
    sales: 4150,
  },
  {
    id: 6,
    name: "云南高山蓝莓鲜果礼盒",
    description: "海拔2000米高山种植，颗颗饱满，酸甜可口，125g×4盒当季新鲜直达。",
    price: "39.90",
    originalPrice: "59.90",
    profit_rate: "0.20",
    images: ["https://picsum.photos/seed/berry6/600/600"],
    sales: 2730,
    tags: ["new"],
  },
  {
    id: 7,
    name: "海天特级鲜味生抽酱油",
    description: "180天天然酿造，鲜味浓郁，炒菜凉拌皆宜，1.9L大容量装。",
    price: "15.90",
    originalPrice: "22.00",
    profit_rate: "0.06",
    images: ["https://picsum.photos/seed/sauce7/600/600"],
    sales: 12400,
  },
  {
    id: 8,
    name: "维达超韧抽纸家庭装",
    description: "3层加厚不易破，柔韧亲肤，湿水不易烂，130抽×24包超值装。",
    price: "42.90",
    originalPrice: "59.90",
    profit_rate: "0.10",
    images: ["https://picsum.photos/seed/tissue8/600/600"],
    sales: 6850,
    tags: ["promotion"],
  },
  {
    id: 9,
    name: "良品铺子靖江猪肉脯",
    description: "精选猪后腿肉，炭火烘烤，薄如蝉翼，香酥不腻，200g袋装。",
    price: "29.90",
    originalPrice: "39.90",
    profit_rate: "0.15",
    images: ["https://picsum.photos/seed/jerky9/600/600"],
    sales: 3410,
    tags: ["promotion"],
  },
  {
    id: 10,
    name: "飞鹤星飞帆婴幼儿配方奶粉",
    description: "专为中国宝宝体质研发，添加OPO结构脂，3段700g罐装。",
    price: "198.00",
    originalPrice: "258.00",
    profit_rate: "0.12",
    images: ["https://picsum.photos/seed/formula10/600/600"],
    sales: 1920,
    tags: ["member_exclusive"],
  },
  {
    id: 11,
    name: "海底捞自热火锅麻辣牛肉",
    description: "一人食火锅，15分钟即热即食，正宗麻辣味，435g大份量。",
    price: "35.90",
    originalPrice: "45.00",
    profit_rate: "0.14",
    images: ["https://picsum.photos/seed/hotpot11/600/600"],
    sales: 7210,
    tags: ["hot"],
  },
  {
    id: 12,
    name: "农夫山泉天然饮用水",
    description: "源自深层地下岩层，天然弱碱性水，清冽甘甜，550ml×24瓶整箱。",
    price: "25.90",
    originalPrice: "36.00",
    profit_rate: "0.08",
    images: ["https://picsum.photos/seed/water12/600/600"],
    sales: 15600,
  },
];
